POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI2IiwiaWQiOiI2M2UwMWQ3NzNkN2QwYTM0NTlhMGNiMGYiLCJpYXQiOjE2NzU2MzIwMDR9.sxaILGVyXjLdb1an7oStlxUPBRm8dN0V_wQbE6pu49g

{
  "title": "This that3",
  "author": "Blim Blam",
  "url": "www.sblipblpo.com",
  "likes": 999
}